### ISSUE TITLE
Error running timer 'coverage redraw buffers'

### ISSUE THREAD

**Issue by martinstannard** [trezona-lecomte/coverage#13]
I'm trying to run coverage on doom-emacs and am getting an error:

```
Error running timer ‘coverage-redraw-buffers’: (wrong-type-argument number-or-marker-p (lines . [1 1 1 1 1 nil 1 1 nil 1 nil nil nil nil 1 nil 1 4 4 nil 4 4 nil 1 nil 1 nil 2 nil nil nil nil 1 1 1 nil nil nil nil nil nil 1 nil 1 nil 1 nil nil nil 4 nil 1 nil 1 0 nil 0 nil nil nil nil nil nil 0 nil nil nil nil nil 1 nil 1 nil nil nil nil nil nil 1 nil nil nil 1 nil 1 nil nil nil])) [3 times]
```
The project is a standard Rails project and the .resultset.json file looks like:

```
 "RSpec": {
    "coverage": {
      "/home/martin/work/scentre/identity_service/app/controllers/auth0/change_email_controller.rb": {
        "lines": [
          1,
          1,
          1,
          null,
          1,
          8,
          8,
          6,
          null,
          6,
          2,
          2,
          2,
          null,
          null,
          4,
          2,
          null,
          2,
          null,
          null,
          6,
          null,
          null,
          1,
          null,
          1,
          12,
          null,
          null,
          1,
          4,
          8,
          null,
          null,
          null
        ]
      },
....
```

Any ideas on what the issue may be?

**Comment by trezona-lecomte** [comment]
Hi @martinstannard it looks like the structure of the `.resultset.json` emitted by simplecov has changed in `0.18.0` (see issues it has caused a CI coverage integration here: https://github.com/codeclimate/test-reporter/issues/413).

**Comment by trezona-lecomte** [comment]
For a quick fix you could downgrade your version of simplecov or transform the `resultset.json` to the old format. In the long term I'll need to update to the new format or transition to a custom formatter.

**Comment by trezona-lecomte** [comment]
For reference the pre-0.18.0 format was:

```
{
  "RSpec": {
    "coverage": {
      "/Users/foo/app/controllers/foos_controller.rb": [
        null,
        null,
        1
      ]
    },
    "timestamp": 1592289182
  }
}
```

**Comment by martinstannard** [comment]
Thanks @trezona-lecomte, I've pinned the gem to '0.17.0` for now, and it's working well. Hopefully someone will step in with a custom formattter at some stage.

Thanks for a very handy package, it's very useful!

**Comment by trezona-lecomte** [comment]
Good to hear @martinstannard, I haven't had much time to work on this package since I originally built it so I'm glad it's still useful.
