### ISSUE TITLE
Search-failedd "\"timestamp\": [0-9]+") [2 times] Quit

### ISSUE THREAD

**Issue by map7** [trezona-lecomte/coverage#5]
I'm using Rails 3.2, RSpec, SimpleCov & emacs 25. When I run my tests it creates a coverage directory and it has a .resultset.json file but I'm getting this error in my _Messages_ buffer;

```
Error running timer ‘coverage-redraw-buffers’: (search-failed "\"timestamp\": [0-9]+")
```

**Comment by trezona-lecomte** [comment]
Hey, sorry about the super late reply to this issue, I completely missed that it had been raised 😞 

If you're still interested in getting this fixed, can you please provide me with a bit more info:

- Have you customised the `coverage-dir` directory at all?
- Are you using git in your project?
- Where does your `.resultset.json` file live, and does it contain a `"timestamp"` field?
- What versions of rspec & simplecov are you using?

I've bootstrapped a Rails 3.2 app with version `0.13.0` of simplecov and version `3.5.4` of rspec, and coverage-mode is working fine in this project, so I haven't been able to reproduce your error yet. Admittedly the code in this package is quite fragile.

Of note is that there are a couple of other packages aiming to do similar things such as https://github.com/twada/coverlay.el and https://github.com/AdamNiederer/cov, so I'm likely going to try those out and figure out a way to consolidate with one of them.
