### ISSUE TITLE
Different languages

### ISSUE THREAD

**Issue by jcubic** [trezona-lecomte/coverage#9]
Do you plan to support different languages?

I've created highlighting for jest JavaScript converage json file (probably will work also with jasmine) Take a look here https://github.com/jcubic/jest-coverage.el

What about PHP I think that I will extend my mode to include php as well (the coverage file is xml based).

**Comment by jcubic** [comment]
The module was renamed to https://github.com/jcubic/coverage.el and it now support php and JavaScript.

Since your package is on melpa you may consider grabbing my code and integrating it with the package.

**Comment by trezona-lecomte** [comment]
Hi @jcubic I'm currently using this only for Ruby myself but will spend a bit of time looking into what it would take to support other languages. Thanks for opening the issue.

**Comment by Technologicat** [comment]
Python would be very useful, too. There's [a Python fork of coverage-mode](https://github.com/Bogdanp/coverage-mode) by @Bogdanp.

Possible approach:

 - `coverage/get-results-for-file` is the backend, needs to have one implementation per target language. Could extract those from the forks posted here?
 - Looking at the value of `major-mode` (for the current buffer), or the file extension (for an arbitrary file), should help detect which backend to invoke.

Integrating these forks into the official package would have the added advantage of easy install in Spacemacs for users of one of the alternative backends. Right now, to get one of them `dotspacemacs-additional-packages` needs something like `(coverage :location (recipe :fetcher github :repo "someuser/coverage"))`, but for the official package on MELPA, just the package name is enough.

Of course, having all backends in the same package would also help users who need more than one language. :)

**Comment by trezona-lecomte** [comment]
Hi @Technologicat, thanks for the suggestion 💯. I appreciate the input.

I will find some time in the next few weeks to take a look at this.

**Comment by trezona-lecomte** [comment]
Sorry I haven't had time to look into this, I'm happy to accept pull requests but as I'm not using `coverage` for anything except Ruby at the moment it's a lot of work to set up projects to be able to test & develop this.
